name: Test And Build Player

on:
  pull_request: {}
  push: { branches: ['+([0-9])?(.{+([0-9]),x}).x', 'master','main', 'next', 'next-major', 'beta', 'alpha'] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.ci-skip-step.outputs.ci-skip }}
      skip-not: ${{ steps.ci-skip-step.outputs.ci-skip-not }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: ci-skip-step
        uses: mstachniuk/ci-skip@master
  buildAndTest:
    needs: init
    if: ${{ needs.init.outputs.skip == 'false' }}
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2020.1.9f1
        targetPlatform:
          - Android
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          lfs: true
      - uses: actions/cache@v2.1.3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.targetPlatform }}
      - uses: webbertakken/unity-test-runner@v1.7
        id: testRunner
        with:
          unityVersion: ${{ matrix.unityVersion }}
      - uses: actions/upload-artifact@v2
        with:
          name: Test results (all modes)
          path: ${{ steps.testRunner.outputs.artifactsPath }}
      - uses: webbertakken/unity-builder@v2.0-aplha-5
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: None
      - uses: actions/upload-artifact@v2
        with:
          name: Build Player
          path: build
  Release:
    name: Release
    runs-on: ubuntu-latest
    needs: [buildAndTest]
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          lfs: true
      - uses: actions/download-artifact@v2
        with:
          name: Build Player
          path: build
      - uses: papeloto/action-zip@v1
        with:
          files: build
          recursive: false
          dest: buildPlayer.zip
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
