name: Build 

on:
  pull_request: {}
  push: { branches: [main] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  buildAndTestForPlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectName:
         - MobileGame
        unityVersion:
          - 2020.1.5f1
        targetPlatform:
          - Android # Build an Android .apk standalone app.
          - iOS # Build an iOS player.
        testMode:
          - playmode
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectName }}/Library
          key: Library- ${{ matrix.projectName }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectName }}-
            Library-
      - uses: webbertakken/unity-test-runner@v1.7
        id: testRunner
        with:
          #projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
      - uses: actions/upload-artifact@v1
        with:
          name: Test results (all modes)
          path: ${{ steps.testRunner.outputs.artifactsPath }}
      - uses: webbertakken/unity-builder@v2.0-aplha-5
        with:
          #projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
